table adqtarjeta

	measure PromedioSaldoTarjeta = ```
			
			AVERAGEX(
			    'adqtarjeta',
			    'adqtarjeta'[monto]
			)
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure VariacionSaldoTarjetas = ```
			
			VAR TotalActual = 
			    CALCULATE(
			        SUM('adqtarjeta'[monto]),
			        'adqtarjeta'[fecadq] >= MIN(Calendario[Date]) && 'adqtarjeta'[fecadq] <= MAX(Calendario[Date]),
			        ALL('adqtarjeta')
			    )
			VAR TotalAnterior = 
			    CALCULATE(
			        SUM('adqtarjeta'[monto])
			    )
			RETURN 
			    TotalActual - TotalAnterior
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure NumeroTotalSaldoTarjetas = ```
			
			CALCULATE(
			    SUM('adqtarjeta'[monto]),
			    DATESBETWEEN(
			        Calendario[Date], 
			        MIN(Calendario[Date]), 
			        MAX(Calendario[Date])
			    )
			)
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column idadqtarjeta
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: idadqtarjeta

		annotation SummarizationSetBy = Automatic

	column fkcliente
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkcliente

		annotation SummarizationSetBy = Automatic

	column fkcampania
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkcampania

		annotation SummarizationSetBy = Automatic

	column fecadq
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		summarizeBy: none
		sourceColumn: fecadq

		variation Variation
			isDefault
			relationship: e175c37f-6fae-41b5-aeeb-1b1a8c442527
			defaultHierarchy: LocalDateTable_a2b7fc0b-240d-441b-9172-72531ad7891d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column cant
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: cant

		annotation SummarizationSetBy = Automatic

	column monto
		dataType: double
		sourceProviderType: float
		summarizeBy: sum
		sourceColumn: monto

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NuevosSaldosPeriodoAnterior =
			
			CALCULATE(
			    SUM(adqtarjeta[monto]),
			    DATEADD(adqtarjeta[fecadq], -1, YEAR)
			)
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition adqtarjeta = m
		mode: import
		source =
				let
				    Source = Sql.Databases("40.79.18.177"),
				    Apployalty = Source{[Name="Apployalty"]}[Data],
				    dbo_adqtarjeta = Apployalty{[Schema="dbo",Item="adqtarjeta"]}[Data]
				in
				    dbo_adqtarjeta

