table afiliacion

	measure VariacionNuevosAfiliados_Absoluta
		isHidden

		changedProperty = IsHidden

	measure CantidadTotalAfiliados = ```
			
			CALCULATE(
			    COUNTROWS(afiliacion),
			    ALL(afiliacion) -- Elimina todos los filtros aplicados
			)
			
			```
		formatString: 0
		isHidden

		changedProperty = IsHidden

	measure VariacionNuevosAfiliados = ```
			
			CALCULATE(COUNTROWS(afiliacion)) - CALCULATE(COUNTROWS(ALL(afiliacion)))
			
			```
		formatString: #,0.00

	column idaf
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: idaf

		annotation SummarizationSetBy = Automatic

	column fkcliente
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkcliente

		annotation SummarizationSetBy = Automatic

	column fkusuario
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkusuario

		annotation SummarizationSetBy = Automatic

	column fecin
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		summarizeBy: none
		sourceColumn: fecin

		variation Variation
			isDefault
			relationship: 94bf30f7-a0d1-47d7-adb4-c5ee9c1431ed
			defaultHierarchy: LocalDateTable_9e3cdf89-5f9e-4fbd-bbce-898d4cfa7d20.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column fecout
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		summarizeBy: none
		sourceColumn: fecout

		variation Variation
			isDefault
			relationship: af912721-d8e5-4efd-bc5e-fc8309c19878
			defaultHierarchy: LocalDateTable_21d4017a-4d17-447b-afb3-8d606731f1d4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column notif
		dataType: string
		sourceProviderType: nvarchar(1)
		summarizeBy: none
		sourceColumn: notif

		annotation SummarizationSetBy = Automatic

	column activo
		dataType: string
		sourceProviderType: nvarchar(1)
		summarizeBy: none
		sourceColumn: activo

		annotation SummarizationSetBy = Automatic

	column PromedioAfiliados = ```
			
			AVERAGEX(
			    SUMMARIZE(
			        Afiliacion, 
			        Afiliacion[fecin], 
			        "Nuevos Afiliados", COUNT(Afiliacion[idaf])
			    ), 
			    [Nuevos Afiliados]
			)
			
			
			```
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NuevosAfiliados = ```
			COUNTROWS(afiliacion)
			
			```
		formatString: 0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition afiliacion = m
		mode: import
		source =
				let
				    Source = Sql.Databases("40.79.18.177"),
				    Apployalty = Source{[Name="Apployalty"]}[Data],
				    dbo_afiliacion = Apployalty{[Schema="dbo",Item="afiliacion"]}[Data]
				in
				    dbo_afiliacion

