table CalendarioGeneral

	measure DiaAnterior = ```
			
			VAR FechaActual = MAX('CalendarioAfiliado'[Date])
			VAR FechaAnterior = FechaActual - 1
			RETURN 
			IF(MAX('CalendarioAfiliado'[Date]) = FechaAnterior, 1, 0)
			
			```
		formatString: 0

	measure SemanaAnterior = ```
			
			VAR FechaActual = MAX('CalendarioAfiliado'[Date])
			VAR InicioSemanaActual = FechaActual - WEEKDAY(FechaActual, 2) + 1  -- Calcula el inicio de la semana actual
			VAR FinSemanaActual = InicioSemanaActual + 6  -- Calcula el fin de la semana actual
			VAR InicioSemanaAnterior = InicioSemanaActual - 7  -- Calcula el inicio de la semana anterior
			VAR FinSemanaAnterior = FinSemanaActual - 7  -- Calcula el fin de la semana anterior
			RETURN 
			IF(MAX('CalendarioAfiliado'[Date]) >= InicioSemanaAnterior && MAX('CalendarioAfiliado'[Date]) <= FinSemanaAnterior, 1, 0)
			
			```
		formatString: 0

	measure QuincenaAnterior = ```
			
			VAR FechaActual = MAX('CalendarioAfiliado'[Date])
			VAR DiaActual = DAY(FechaActual)
			VAR QuincenaActual = IF(DiaActual <= 15, 1, 2)
			VAR FechaInicioQuincenaAnterior = IF(QuincenaActual = 1, DATE(YEAR(FechaActual), MONTH(FechaActual), 16), DATE(YEAR(FechaActual), MONTH(FechaActual), 1))
			VAR FechaFinQuincenaAnterior = IF(QuincenaActual = 1, DATE(YEAR(FechaActual), MONTH(FechaActual), 1), DATE(YEAR(FechaActual), MONTH(FechaActual) + 1, 15))
			RETURN 
			IF(MAX('CalendarioAfiliado'[Date]) >= FechaInicioQuincenaAnterior && MAX('CalendarioAfiliado'[Date]) <= FechaFinQuincenaAnterior, 1, 0)
			
			```
		formatString: 0

	measure MesAnterior = ```
			
			VAR FechaActual = MAX('CalendarioAfiliado'[Date])
			VAR MesActual = MONTH(FechaActual)
			VAR AnioActual = YEAR(FechaActual)
			VAR FechaInicioMesAnterior = IF(MesActual = 1, DATE(AnioActual - 1, 12, 1), DATE(AnioActual, MesActual - 1, 1))
			VAR FechaFinMesAnterior = EOMONTH(FechaInicioMesAnterior, 0)
			RETURN 
			IF(MAX('CalendarioAfiliado'[Date]) >= FechaInicioMesAnterior && MAX('CalendarioAfiliado'[Date]) <= FechaFinMesAnterior, 1, 0)
			
			```
		formatString: 0

	column Date
		formatString: General Date
		summarizeBy: none
		isNameInferred
		sourceColumn: [Date]

		variation Variation
			isDefault
			relationship: e6096dff-c9b0-47f2-937f-577c693ed001
			defaultHierarchy: LocalDateTable_97f101e4-a3d5-4138-9aed-f35b25f07606.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Year
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Year]

		annotation SummarizationSetBy = Automatic

	column Month
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Month]

		annotation SummarizationSetBy = Automatic

	column MonthName
		summarizeBy: none
		isNameInferred
		sourceColumn: [MonthName]

		annotation SummarizationSetBy = Automatic

	column MonthYear
		summarizeBy: none
		isNameInferred
		sourceColumn: [MonthYear]

		annotation SummarizationSetBy = Automatic

	column Quarter
		summarizeBy: none
		isNameInferred
		sourceColumn: [Quarter]

		annotation SummarizationSetBy = Automatic

	column WeekDay
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [WeekDay]

		annotation SummarizationSetBy = Automatic

	column WeekDayName
		summarizeBy: none
		isNameInferred
		sourceColumn: [WeekDayName]

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		isNameInferred
		sourceColumn: [IsWeekend]

		annotation SummarizationSetBy = Automatic

	column YearMonthNumber
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [YearMonthNumber]

		annotation SummarizationSetBy = Automatic

	column YearWeekNumber
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [YearWeekNumber]

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		isNameInferred
		sourceColumn: [IsHoliday]

		annotation SummarizationSetBy = Automatic

	column WeekNum = WEEKNUM(CalendarioGeneral[Date],2)
		formatString: 0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Inicio Mes' = STARTOFMONTH(CalendarioGeneral[Date])
		formatString: General Date
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 4f052d2c-467b-47ed-b773-f28022bc9138
			defaultHierarchy: LocalDateTable_47a02d7f-fca7-4457-bd14-3aa15ee423f0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Semana 1er dia' = ```
			WEEKNUM(STARTOFMONTH(CalendarioGeneral[Date]), 2)
			
			```
		formatString: 0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Semana del mes' = 1+CalendarioGeneral[WeekNum]-CalendarioGeneral[Semana 1er dia]
		formatString: 0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Día del Mes' = ```
			DAY(CalendarioGeneral[Date])
			
			```
		formatString: 0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Quincena = ```
			
			IF(DAY(CalendarioGeneral[Date]) <= 15, "Primera Quincena", "Segunda Quincena")
			
			```
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition CalendarioGeneral = calculated
		mode: import
		source = ```
				
				VAR MinFechaAfiliado = CALCULATE(MIN('dwh Dim_Afiliado'[FechaRegistroWebo])) -- Fecha mínima en Afiliados
				VAR MaxFechaAfiliado = CALCULATE(MAX('dwh Dim_Afiliado'[FechaRegistroWebo])) -- Fecha máxima en Afiliados
				VAR MinFechaTienda = CALCULATE(MIN('dwh Dim_Tienda'[FechaInicio])) -- Fecha mínima en Tiendas
				VAR MaxFechaTienda = CALCULATE(MAX('dwh Dim_Tienda'[FechaInicio])) -- Fecha máxima en Tiendas
				VAR MinFechaTarjeta = CALCULATE(MIN('dwh Dim_Tarjeta'[FechaActivo])) -- Fecha mínima en Tarjetas
				VAR MaxFechaTarjeta = CALCULATE(MAX('dwh Dim_Tarjeta'[FechaActivo])) -- Fecha máxima en Tarjetas
				
				-- Fecha mínima y máxima general calculada con la función MINX/MAXX en una tabla de 1 fila
				VAR MinFechaGeneral = MINX({MinFechaAfiliado, MinFechaTienda, MinFechaTarjeta}, [Value]) 
				VAR MaxFechaGeneral = MAXX({MaxFechaAfiliado, MaxFechaTienda, MaxFechaTarjeta}, [Value]) 
				
				RETURN
				ADDCOLUMNS(
				    CALENDAR(MinFechaGeneral, MaxFechaGeneral), -- Crea el calendario entre las fechas mínima y máxima general
				    "Year", YEAR([Date]),
				    "Month", MONTH([Date]),
				    "MonthName", FORMAT([Date], "MMMM"),
				    "MonthYear", FORMAT([Date], "MMM YYYY"),
				    "Quarter", "Q" & FORMAT([Date], "Q"),
				    "WeekDay", WEEKDAY([Date]),
				    "WeekDayName", FORMAT([Date], "dddd"),
				    "IsWeekend", IF(WEEKDAY([Date], 2) >= 6, TRUE, FALSE),
				    "YearMonthNumber", YEAR([Date]) * 100 + MONTH([Date]),
				    "YearWeekNumber", YEAR([Date]) * 100 + WEEKNUM([Date], 2),
				    "IsHoliday", FALSE() -- Puedes agregar lógica para días festivos si tienes datos
				)
				
				```

	annotation PBI_Id = 82d75f976dad4ff8badbb1c1188abe87

