table CalendarioGeneral

	measure UltimoAnoMedida =
			
			VAR FechaFinal = TODAY()
			RETURN DATE(YEAR(FechaFinal) - 1, 1, 1)
		formatString: General Date

	measure UltimoDiaMedida =
			
			VAR FechaFinal = TODAY()
			RETURN FechaFinal - 1
		formatString: General Date

	measure UltimoMesMedida =
			
			VAR FechaFinal = TODAY()
			RETURN EOMONTH(FechaFinal, -1) + 1
		formatString: General Date

	measure UltimaSemana =
			
			VAR FechaFinal = TODAY()
			RETURN FechaFinal - 7
		formatString: General Date

	measure FiltroDinamico = ```
			
			VAR FechaFinal = MAX('CalendarioGeneral'[Date])  -- Obtener la fecha máxima del contexto
			VAR UltimoDia = FechaFinal - 1  -- Último día
			VAR UltimaSemana = FechaFinal - 7  -- Última semana
			VAR UltimoMes = EOMONTH(FechaFinal, -1) + 1  -- Primer día del mes anterior
			VAR UltimoAno = DATE(YEAR(FechaFinal) - 1, MONTH(FechaFinal), DAY(FechaFinal))  -- Mismo día pero un año antes
			
			VAR Seleccionado = SELECTEDVALUE(TablaFiltro[Periodo], "Ninguno")  -- Obtener el valor seleccionado en el slicer
			
			RETURN
			    SWITCH(
			        Seleccionado,
			        "Último día", UltimoDia,
			        "Última semana", UltimaSemana,
			        "Último mes", UltimoMes,
			        "Último año", UltimoAno,
			        BLANK()  -- Si no hay selección, no retorna ningún valor
			    )
			
			```

	column Date
		formatString: General Date
		summarizeBy: none
		isNameInferred
		sourceColumn: [Date]

		variation Variation
			isDefault
			relationship: a545dd53-f2d0-4613-8b5e-f58056442009
			defaultHierarchy: LocalDateTable_97f101e4-a3d5-4138-9aed-f35b25f07606.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Year
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Year]

		annotation SummarizationSetBy = Automatic

	column Month
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Month]

		annotation SummarizationSetBy = Automatic

	column MonthName
		summarizeBy: none
		isNameInferred
		sourceColumn: [MonthName]

		annotation SummarizationSetBy = Automatic

	column MonthYear
		summarizeBy: none
		isNameInferred
		sourceColumn: [MonthYear]

		annotation SummarizationSetBy = Automatic

	column Quarter
		summarizeBy: none
		isNameInferred
		sourceColumn: [Quarter]

		annotation SummarizationSetBy = Automatic

	column WeekDay
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [WeekDay]

		annotation SummarizationSetBy = Automatic

	column WeekDayName
		summarizeBy: none
		isNameInferred
		sourceColumn: [WeekDayName]

		annotation SummarizationSetBy = Automatic

	column IsWeekend
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		isNameInferred
		sourceColumn: [IsWeekend]

		annotation SummarizationSetBy = Automatic

	column YearMonthNumber
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [YearMonthNumber]

		annotation SummarizationSetBy = Automatic

	column YearWeekNumber
		formatString: 0
		summarizeBy: sum
		isNameInferred
		sourceColumn: [YearWeekNumber]

		annotation SummarizationSetBy = Automatic

	column IsHoliday
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		isNameInferred
		sourceColumn: [IsHoliday]

		annotation SummarizationSetBy = Automatic

	column WeekNum = WEEKNUM(CalendarioGeneral[Date],2)
		formatString: 0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Inicio Mes' = STARTOFMONTH(CalendarioGeneral[Date])
		formatString: General Date
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 4f052d2c-467b-47ed-b773-f28022bc9138
			defaultHierarchy: LocalDateTable_47a02d7f-fca7-4457-bd14-3aa15ee423f0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Semana 1er dia' = ```
			WEEKNUM(STARTOFMONTH(CalendarioGeneral[Date]), 2)
			
			```
		formatString: 0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Semana del mes' = 1+CalendarioGeneral[WeekNum]-CalendarioGeneral[Semana 1er dia]
		formatString: 0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Día del Mes' = ```
			DAY(CalendarioGeneral[Date])
			
			```
		formatString: 0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Quincena = ```
			
			IF(DAY(CalendarioGeneral[Date]) <= 15, "Primera Quincena", "Segunda Quincena")
			
			```
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column UltimaSemanaMedida =
			
			VAR FechaFinal = MAXX(ALLSELECTED('CalendarioGeneral'), 'CalendarioGeneral'[Date])
			RETURN FechaFinal - 7
		formatString: General Date
		summarizeBy: none

		variation Variation
			isDefault
			relationship: f8acf425-5d7f-42b2-aff2-719c4f662872
			defaultHierarchy: LocalDateTable_d7f24b45-5c35-4499-9096-14e7bc3e30f1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition CalendarioGeneral = calculated
		mode: import
		source = ```
				VAR MinFechaAfiliado = CALCULATE(MIN('dwh Dim_Afiliado'[FechaRegistroWebo])) -- Fecha mínima en Afiliados
				VAR MaxFechaAfiliado = CALCULATE(MAX('dwh Dim_Afiliado'[FechaRegistroWebo])) -- Fecha máxima en Afiliados
				VAR MinFechaTienda = CALCULATE(MIN('dwh Dim_Tienda'[FechaInicio])) -- Fecha mínima en Tiendas
				VAR MaxFechaTienda = CALCULATE(MAX('dwh Dim_Tienda'[FechaInicio])) -- Fecha máxima en Tiendas
				VAR MinFechaTarjeta = CALCULATE(MIN('dwh Dim_Tarjeta'[FechaActivo])) -- Fecha mínima en Tarjetas
				VAR MaxFechaTarjeta = CALCULATE(MAX('dwh Dim_Tarjeta'[FechaActivo])) -- Fecha máxima en Tarjetas
				VAR MinFechaTiempo = CALCULATE(MIN('dwh Dim_Tiempo'[Fecha])) -- Fecha mínima en Tiempo
				VAR MaxFechaTiempo = CALCULATE(MAX('dwh Dim_Tiempo'[Fecha])) -- Fecha máxima en Tiempo
				
				-- Fecha mínima y máxima general calculada con la función MINX/MAXX en una tabla de 1 fila
				VAR MinFechaGeneral = MINX({MinFechaAfiliado, MinFechaTienda, MinFechaTarjeta, MinFechaTiempo}, [Value]) 
				VAR MaxFechaGeneral = MAXX({MaxFechaAfiliado, MaxFechaTienda, MaxFechaTarjeta, MaxFechaTiempo}, [Value]) 
				
				RETURN
				ADDCOLUMNS(
				    CALENDAR(MinFechaGeneral, MaxFechaGeneral), -- Crea el calendario entre las fechas mínima y máxima general
				    "Year", YEAR([Date]),
				    "Month", MONTH([Date]),
				    "MonthName", FORMAT([Date], "MMMM"),
				    "MonthYear", FORMAT([Date], "MMM YYYY"),
				    "Quarter", "Q" & FORMAT([Date], "Q"),
				    "WeekDay", WEEKDAY([Date]),
				    "WeekDayName", FORMAT([Date], "dddd"),
				    "IsWeekend", IF(WEEKDAY([Date], 2) >= 6, TRUE, FALSE),
				    "YearMonthNumber", YEAR([Date]) * 100 + MONTH([Date]),
				    "YearWeekNumber", YEAR([Date]) * 100 + WEEKNUM([Date], 2),
				    "IsHoliday", FALSE() -- Puedes agregar lógica para días festivos si tienes datos
				)
				
				```

	annotation PBI_Id = 82d75f976dad4ff8badbb1c1188abe87

