table 'dwh Fact_Facturacion'

	measure 'Monto Total Facturado' = ```
			
			VAR FechaRaiz = Min('dwh Dim_Tiempo'[Fecha])
			VAR FechaSeleccionada = MAX('dwh Dim_Tiempo'[Fecha])
			RETURN 
			CALCULATE(
			    SUM('dwh Fact_Facturacion'[Importe]),
			    'dwh Dim_Tiempo'[Fecha] <= FechaSeleccionada
			)
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variación Monto Facturado' = ```
			
			VAR FechaRaiz = MIN('dwh Dim_Tiempo'[Fecha])
			VAR Fin = MAX('dwh Dim_Tiempo'[Fecha])
			
			VAR MontoInicio = CALCULATE(
			    SUM('dwh Fact_Facturacion'[Importe]),
			    'dwh Dim_Tiempo'[Fecha] <= FechaRaiz
			)
			
			VAR MontoFin = CALCULATE(
			    SUM('dwh Fact_Facturacion'[Importe]),
			    'dwh Dim_Tiempo'[Fecha] <= Fin
			)
			
			RETURN MontoFin - MontoInicio
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promedio Facturado' = ```
			
			VAR FechaSeleccionada = MAX('dwh Dim_Tiempo'[Fecha])
			RETURN 
			CALCULATE(
			    AVERAGE('dwh Fact_Facturacion'[Importe]),
			    'dwh Dim_Tiempo'[Fecha] <= FechaSeleccionada
			)
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Frecuencia Promedio' = ```
			
			AVERAGEX(
			    SUMMARIZE(
			        'dwh Fact_Facturacion',
			        'dwh Fact_Facturacion'[KeyAfiliado],
			        'dwh Dim_Tiempo'[Fecha],
			        "ConsumosPorAfiliado", COUNT('dwh Fact_Facturacion'[KeyFactFacturacion])
			    ),
			    [ConsumosPorAfiliado]
			)
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ValorMonetarioPromedio = ```
			
			AVERAGEX(
			    SUMMARIZE(
			        'dwh Fact_Facturacion',
			        'dwh Fact_Facturacion'[KeyAfiliado],
			        'dwh Dim_Tiempo'[Fecha],
			        "ImportePromedio", SUM('dwh Fact_Facturacion'[Importe])
			    ),
			    [ImportePromedio]
			)
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Valor Monetario Semanal' = ```
			
			VAR FechaSeleccionada = MAX('dwh Dim_Tiempo'[Fecha]) -- Última fecha disponible en el contexto
			VAR FechaInicio = FechaSeleccionada - 6 -- Rango de los últimos 7 días
			
			RETURN 
			    CALCULATE(
			        AVERAGE('dwh Fact_Facturacion'[Importe]),
			        'dwh Dim_Tiempo'[Fecha] >= FechaInicio && 'dwh Dim_Tiempo'[Fecha] <= FechaSeleccionada,
			        'dwh Dim_Tiempo'[Fecha]<> BLANK() -- Asegura que no cuenta valores en blanco
			    )
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure VisitasPromedio = ```
			
			DIVIDE(
			    COUNT('dwh Fact_Facturacion'[KeyFactFacturacion]),
			    DISTINCTCOUNT('dwh Dim_Tiempo'[Fecha])
			)
			
			```
		formatString: 0

	column KeyFactFacturacion
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: KeyFactFacturacion

		annotation SummarizationSetBy = Automatic

	column KeyFechaFacturacion
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyFechaFacturacion

		annotation SummarizationSetBy = Automatic

	column KeyAfiliado
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyAfiliado

		annotation SummarizationSetBy = Automatic

	column KeyRangoEdad
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyRangoEdad

		annotation SummarizationSetBy = Automatic

	column KeyEmpresa
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyEmpresa

		annotation SummarizationSetBy = Automatic

	column KeyTienda
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: KeyTienda

		annotation SummarizationSetBy = Automatic

	column KeyPromocion
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyPromocion

		annotation SummarizationSetBy = Automatic

	column KeyPrograma
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyPrograma

		annotation SummarizationSetBy = Automatic

	column StickersEntregados
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: StickersEntregados

		annotation SummarizationSetBy = Automatic

	column Importe
		dataType: double
		summarizeBy: sum
		sourceColumn: Importe

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column KeyTarjeta
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyTarjeta

		annotation SummarizationSetBy = Automatic

	partition 'dwh Fact_Facturacion' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("LocalHost"),
				    ApployaltyDWH = Source{[Name="ApployaltyDWH"]}[Data],
				    dwh_Fact_Facturacion = ApployaltyDWH{[Schema="dwh",Item="Fact_Facturacion"]}[Data]
				in
				    dwh_Fact_Facturacion

