table 'dwh Fact_Promociones'

	measure TotalPromocionesActivas = ```
			
			CALCULATE(
			    COUNT('dwh Fact_Promociones'[KeyFactPromocion]),
			    'dwh Fact_Promociones'[FlagPromocionActiva] = 1
			)
			
			```
		formatString: 0

	measure TotalPromocionesRedimidas = ```
			
			CALCULATE(
			    COUNT('dwh Fact_Promociones'[KeyFactPromocion]),
			    'dwh Fact_Promociones'[FlagPromocionRedimida] = 1
			)
			
			```
		formatString: 0

	measure TotalPromocionesVencidas = ```
			
			CALCULATE(
			    COUNT('dwh Fact_Promociones'[KeyFactPromocion]),
			    'dwh Fact_Promociones'[FlagCuponVencido] = 1
			)
			
			```
		formatString: 0

	measure PromedioDiasActivacion = ```
			
			AVERAGE('dwh Fact_Promociones'[DiasHastaActivarPromocion])
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column KeyFactPromocion
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: KeyFactPromocion

		annotation SummarizationSetBy = Automatic

	column KeyFechaCorte
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: KeyFechaCorte

		annotation SummarizationSetBy = Automatic

	column KeyAfiliado
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyAfiliado

		annotation SummarizationSetBy = Automatic

	column KeyRangoEdad
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyRangoEdad

		annotation SummarizationSetBy = Automatic

	column KeyEmpresa
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyEmpresa

		annotation SummarizationSetBy = Automatic

	column KeyCuponPromocional
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyCuponPromocional

		annotation SummarizationSetBy = Automatic

	column KeyPromocion
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyPromocion

		annotation SummarizationSetBy = Automatic

	column FechaCreacion
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: FechaCreacion

		variation Variation
			isDefault
			relationship: e6d1375c-82ca-4873-bbad-2fff50fa0a5d
			defaultHierarchy: LocalDateTable_8344b2c1-39ef-4c2d-a4e9-f966fd4fa649.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FechaUso
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: FechaUso

		variation Variation
			isDefault
			relationship: bafefc67-904d-4dec-bb4c-e544667b110d
			defaultHierarchy: LocalDateTable_95866b5e-6ad7-40fe-af8b-b8b28a5fa3dc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FlagPromocionActiva
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: FlagPromocionActiva

		annotation SummarizationSetBy = Automatic

	column FlagPromocionActivaAcumulado
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: FlagPromocionActivaAcumulado

		annotation SummarizationSetBy = Automatic

	column FlagPromocionRedimida
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: FlagPromocionRedimida

		annotation SummarizationSetBy = Automatic

	column FlagPromocionRedimidaAcumulado
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: FlagPromocionRedimidaAcumulado

		annotation SummarizationSetBy = Automatic

	column FlagCuponVencido
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: FlagCuponVencido

		annotation SummarizationSetBy = Automatic

	column FlagCuponVencidoAcumulado
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: FlagCuponVencidoAcumulado

		annotation SummarizationSetBy = Automatic

	column DiasHastaActivarPromocion
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: DiasHastaActivarPromocion

		annotation SummarizationSetBy = Automatic

	column DiasHastaRedimirPromocion
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: DiasHastaRedimirPromocion

		annotation SummarizationSetBy = Automatic

	partition 'dwh Fact_Promociones' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("40.79.18.177"),
				    ApployaltyDWH = Source{[Name="ApployaltyDWH"]}[Data],
				    dwh_Fact_Promociones = ApployaltyDWH{[Schema="dwh",Item="Fact_Promociones"]}[Data]
				in
				    dwh_Fact_Promociones

