table 'dwh Fact_Facturacion'

	measure TotalFacturado = ```
			
			VAR FechaInicio = SELECTEDVALUE(UltimasFechasGeneral[Fecha Inicial])
			VAR FechaFinal = SELECTEDVALUE(UltimasFechasGeneral[Fecha Final])
			
			-- Limitar las fechas del rango
			VAR FechaMin = MIN('CalendarioGeneral'[Date])
			VAR FechaMax = MAX('CalendarioGeneral'[Date])
			
			RETURN  
			COALESCE(
			CALCULATE(  
			    SUM('dwh Fact_Facturacion'[Importe]),  
			    'dwh Dim_Tiempo'[Fecha] >= MAX(FechaInicio, FechaMin) &&  
			    'dwh Dim_Tiempo'[Fecha] <= MIN(FechaFinal, FechaMax) && 
			    'dwh Dim_Tiempo'[Fecha] <= FechaMax  
			),"NA")  
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure VariacionMontoFacturado = ```
			
			VAR FechaInicio = SELECTEDVALUE(UltimasFechasGeneral[Fecha Inicial])
			VAR FechaFinal = SELECTEDVALUE(UltimasFechasGeneral[Fecha Final])
			
			-- Limitar las fechas del rango
			VAR FechaMin = MIN('CalendarioGeneral'[Date])
			VAR FechaMax = MAX('CalendarioGeneral'[Date])
			
			-- Monto facturado hasta la FechaInicio
			VAR MontoHastaInicio = 
			    CALCULATE(
			        SUM('dwh Fact_Facturacion'[Importe]),
			        'dwh Dim_Tiempo'[Fecha] <= MAX(FechaInicio, FechaMin) &&
			        'dwh Dim_Tiempo'[Fecha] <= FechaMax
			    )
			
			-- Monto facturado hasta la FechaFinal
			VAR MontoHastaFin = 
			    CALCULATE(
			        SUM('dwh Fact_Facturacion'[Importe]),
			        'dwh Dim_Tiempo'[Fecha] <= MIN(FechaFinal, FechaMax) &&
			        'dwh Dim_Tiempo'[Fecha] <= FechaMax
			    )
			
			-- Variación entre los dos períodos
			RETURN COALESCE(MontoHastaFin - MontoHastaInicio, "NA")
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PromedioFacturado = ```
			
			VAR FechaInicio = SELECTEDVALUE(UltimasFechasGeneral[Fecha Inicial])  -- Fecha de inicio seleccionada
			VAR FechaFinal = SELECTEDVALUE(UltimasFechasGeneral[Fecha Final])    -- Fecha final seleccionada
			
			-- Limitar las fechas del rango
			VAR FechaMin = MIN('CalendarioGeneral'[Date])  -- Fecha mínima del calendario
			VAR FechaMax = MAX('CalendarioGeneral'[Date])  -- Fecha máxima del calendario
			
			-- Calcular la fecha seleccionada
			VAR FechaSeleccionada = MAX('dwh Dim_Tiempo'[Fecha])
			
			RETURN
			COALESCE(
			CALCULATE(
			    AVERAGE('dwh Fact_Facturacion'[Importe]), 
			    'dwh Dim_Tiempo'[Fecha] <= FechaSeleccionada,
			    'dwh Dim_Tiempo'[Fecha] >= FechaInicio,  -- Asegurarse que esté dentro del rango de fechas
			    'dwh Dim_Tiempo'[Fecha] <= FechaFinal    -- Asegurarse que esté dentro del rango de fechas
			)
			, "NA")
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Frecuencia Promedio' = ```
			
			AVERAGEX(
			    SUMMARIZE(
			        'dwh Fact_Facturacion',
			        'dwh Fact_Facturacion'[KeyAfiliado],
			        'dwh Dim_Tiempo'[Fecha],
			        "ConsumosPorAfiliado", COUNT('dwh Fact_Facturacion'[KeyFactFacturacion])
			    ),
			    [ConsumosPorAfiliado]
			)
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ValorMonetarioPromedio = ```
			
			AVERAGEX(
			    SUMMARIZE(
			        'dwh Fact_Facturacion',
			        'dwh Fact_Facturacion'[KeyAfiliado],
			        'dwh Dim_Tiempo'[Fecha],
			        "ImportePromedio", SUM('dwh Fact_Facturacion'[Importe])
			    ),
			    [ImportePromedio]
			)
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Valor Monetario Semanal' = ```
			
			VAR FechaSeleccionada = MAX('dwh Dim_Tiempo'[Fecha]) -- Última fecha disponible en el contexto
			VAR FechaInicio = FechaSeleccionada - 6 -- Rango de los últimos 7 días
			
			RETURN 
			COALESCE(
			    CALCULATE(
			        AVERAGE('dwh Fact_Facturacion'[Importe]),
			        'dwh Dim_Tiempo'[Fecha] >= FechaInicio && 'dwh Dim_Tiempo'[Fecha] <= FechaSeleccionada,
			        'dwh Dim_Tiempo'[Fecha]<> BLANK() -- Asegura que no cuenta valores en blanco
			    )
			, "NA")
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure VisitasPromedio = ```
			
			DIVIDE(
			    COUNT('dwh Fact_Facturacion'[KeyFactFacturacion]),
			    DISTINCTCOUNT('dwh Dim_Tiempo'[Fecha])
			)
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ValorMonetarioPromedioSeleccionado = ```
			
			VAR SelectedUser = SELECTEDVALUE('dwh Dim_Afiliado'[Email])
			RETURN
			    IF(
			        ISBLANK(SelectedUser),
			        "NA",
			        FORMAT([ValorMonetarioPromedio], "0.00")
			    )
			
			```

	column KeyFactFacturacion
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: KeyFactFacturacion

		annotation SummarizationSetBy = Automatic

	column KeyFechaFacturacion
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyFechaFacturacion

		annotation SummarizationSetBy = Automatic

	column KeyAfiliado
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyAfiliado

		annotation SummarizationSetBy = Automatic

	column KeyRangoEdad
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyRangoEdad

		annotation SummarizationSetBy = Automatic

	column KeyEmpresa
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyEmpresa

		annotation SummarizationSetBy = Automatic

	column KeyTienda
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: KeyTienda

		annotation SummarizationSetBy = Automatic

	column KeyPromocion
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyPromocion

		annotation SummarizationSetBy = Automatic

	column KeyPrograma
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyPrograma

		annotation SummarizationSetBy = Automatic

	column StickersEntregados
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: StickersEntregados

		annotation SummarizationSetBy = Automatic

	column Importe
		dataType: double
		summarizeBy: sum
		sourceColumn: Importe

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column KeyTarjeta
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyTarjeta

		annotation SummarizationSetBy = Automatic

	partition 'dwh Fact_Facturacion' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("40.79.18.177"),
				    ApployaltyDWH = Source{[Name="ApployaltyDWH"]}[Data],
				    dwh_Fact_Facturacion = ApployaltyDWH{[Schema="dwh",Item="Fact_Facturacion"]}[Data]
				in
				    dwh_Fact_Facturacion

