table 'dwh Dim_Tiempo'

	column KeyTiempo
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyTiempo

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: dd/mm/yyyy
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = User

	column month
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = User

	column day
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = User

	column week
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: week

		annotation SummarizationSetBy = User

	column Periodo
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: Periodo

		annotation SummarizationSetBy = Automatic

	column 'Fecha Fixed' = DATEVALUE([Fecha])
		formatString: General Date
		summarizeBy: none

		variation Variation
			isDefault
			relationship: e12d0439-44bf-4e5c-be33-f7dc1e7b26f4
			defaultHierarchy: LocalDateTable_2379fe0a-2395-4b4d-bd24-a3ee06f28d39.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column PeriodoDelDia = ```
			
			SWITCH(
			    TRUE(),
			    HOUR('dwh Dim_Tiempo'[Fecha Fixed]) >= 6 && HOUR('dwh Dim_Tiempo'[Fecha Fixed]) <= 11, "Mañana (6:00 - 12:00)",
			    HOUR('dwh Dim_Tiempo'[Fecha Fixed]) >= 12 && HOUR('dwh Dim_Tiempo'[Fecha Fixed]) <= 17, "Tarde (12:00 - 18:00)",
			    HOUR('dwh Dim_Tiempo'[Fecha Fixed]) >= 18 && HOUR('dwh Dim_Tiempo'[Fecha Fixed]) <= 23, "Noche (18:00 - 24:00)",
			    "NA"
			)
			
			```
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'dwh Dim_Tiempo' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("40.79.18.177"),
				    ApployaltyDWH = Source{[Name="ApployaltyDWH"]}[Data],
				    dwh_Dim_Tiempo = ApployaltyDWH{[Schema="dwh",Item="Dim_Tiempo"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dwh_Dim_Tiempo,{{"Dia", "day"}, {"Mes", "month"}, {"Año", "year"}, {"Semana", "week"}})
				in
				    #"Renamed Columns"

