table 'dwh Dim_Tarjeta'

	measure TotalTarjetasActivadas = ```
			
			VAR FechaInicio = SELECTEDVALUE(UltimasFechasGeneral[Fecha Inicial])
			VAR FechaFinal = SELECTEDVALUE(UltimasFechasGeneral[Fecha Final])
			
			-- Limitar las fechas del rango
			VAR FechaMin = MIN('CalendarioGeneral'[Date])  -- Fecha mínima del calendario
			VAR FechaMax = MAX('CalendarioGeneral'[Date])  -- Fecha máxima del calendario
			
			RETURN
			COALESCE(
			CALCULATE(  
			    COUNTROWS('dwh Dim_Tarjeta'),  
			    'dwh Dim_Tarjeta'[FechaActivo] >= MAX(FechaInicio, FechaMin) &&  
			    'dwh Dim_Tarjeta'[FechaActivo] <= MIN(FechaFinal, FechaMax) && 
			    'dwh Dim_Tarjeta'[FechaActivo] <= FechaMax &&  -- Limita a las fechas del calendario general
			    NOT ISBLANK('dwh Dim_Tarjeta'[FechaActivo])  
			)  
			,"NA")
			```
		formatString: 0

	measure VariacionTarjetasActivas = ```
			
			VAR FechaInicio = SELECTEDVALUE(UltimasFechasGeneral[Fecha Inicial])
			VAR FechaFinal = SELECTEDVALUE(UltimasFechasGeneral[Fecha Final])
			
			-- Limitar las fechas del rango
			VAR FechaMin = MIN('CalendarioGeneral'[Date])  -- Fecha mínima del calendario
			VAR FechaMax = MAX('CalendarioGeneral'[Date])  -- Fecha máxima del calendario
			VAR FechaInicio = SELECTEDVALUE(UltimasFechasGeneral[Fecha Inicial])
			VAR FechaFinal = SELECTEDVALUE(UltimasFechasGeneral[Fecha Final])
			
			-- Limitar las fechas del rango
			VAR FechaMin = MIN('CalendarioGeneral'[Date])  -- Fecha mínima del calendario
			VAR FechaMax = MAX('CalendarioGeneral'[Date])  -- Fecha máxima del calendario
			
			-- Tarjetas activas hasta la FechaInicio
			-- Tarjetas activas hasta la FechaInicio
			VAR TarjetasActivasHastaInicio = 
			    CALCULATE(
			        COUNT('dwh Dim_Tarjeta'[KeyTarjeta]),
			        'dwh Dim_Tarjeta'[FechaActivo] <= MAX(FechaInicio, FechaMin) &&
			        'dwh Dim_Tarjeta'[FechaActivo] <= FechaMax  -- Limita a las fechas del calendario general
			        'dwh Dim_Tarjeta'[FechaActivo] <= MAX(FechaInicio, FechaMin) &&
			        'dwh Dim_Tarjeta'[FechaActivo] <= FechaMax  -- Limita a las fechas del calendario general
			    )
			
			-- Tarjetas activas hasta la FechaFinal
			-- Tarjetas activas hasta la FechaFinal
			VAR TarjetasActivasHastaFin = 
			    CALCULATE(
			        COUNT('dwh Dim_Tarjeta'[KeyTarjeta]),
			        'dwh Dim_Tarjeta'[FechaActivo] <= MIN(FechaFinal, FechaMax) &&
			        'dwh Dim_Tarjeta'[FechaActivo] <= FechaMax  -- Limita a las fechas del calendario general
			        'dwh Dim_Tarjeta'[FechaActivo] <= MIN(FechaFinal, FechaMax) &&
			        'dwh Dim_Tarjeta'[FechaActivo] <= FechaMax  -- Limita a las fechas del calendario general
			    )
			
			-- Variación entre los dos períodos
			RETURN COALESCE(TarjetasActivasHastaFin - TarjetasActivasHastaInicio,"NA")
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PromedioTarjetasActivadasPorDia = ```
			
			VAR FechaInicio = SELECTEDVALUE(UltimasFechasGeneral[Fecha Inicial])
			VAR FechaFinal = SELECTEDVALUE(UltimasFechasGeneral[Fecha Final])
			
			-- Limitar las fechas del rango
			VAR FechaMin = MIN('CalendarioGeneral'[Date])  -- Fecha mínima del calendario
			VAR FechaMax = MAX('CalendarioGeneral'[Date])  -- Fecha máxima del calendario
			
			-- Calcular los días únicos en el rango
			VAR FechaInicio = SELECTEDVALUE(UltimasFechasGeneral[Fecha Inicial])
			VAR FechaFinal = SELECTEDVALUE(UltimasFechasGeneral[Fecha Final])
			
			-- Limitar las fechas del rango
			VAR FechaMin = MIN('CalendarioGeneral'[Date])  -- Fecha mínima del calendario
			VAR FechaMax = MAX('CalendarioGeneral'[Date])  -- Fecha máxima del calendario
			
			-- Calcular los días únicos en el rango
			VAR DiasEnRango = 
			    CALCULATE(
			        COUNTROWS(VALUES('dwh Dim_Tarjeta'[FechaActivo])),  -- Cuenta los días únicos dentro del rango
			        'dwh Dim_Tarjeta'[FechaActivo] >= MAX(FechaInicio, FechaMin) && 
			        'dwh Dim_Tarjeta'[FechaActivo] <= MIN(FechaFinal, FechaMax) &&  -- Limita a las fechas del calendario general
			        'dwh Dim_Tarjeta'[FechaActivo] <= FechaMax
			        'dwh Dim_Tarjeta'[FechaActivo] >= MAX(FechaInicio, FechaMin) && 
			        'dwh Dim_Tarjeta'[FechaActivo] <= MIN(FechaFinal, FechaMax) &&  -- Limita a las fechas del calendario general
			        'dwh Dim_Tarjeta'[FechaActivo] <= FechaMax
			    )
			
			-- Calcular el total de tarjetas activadas en el rango
			-- Calcular el total de tarjetas activadas en el rango
			VAR TotalTarjetasActivadas = 
			    CALCULATE(
			        COUNTROWS('dwh Dim_Tarjeta'),  -- Cuenta todas las tarjetas activadas
			        'dwh Dim_Tarjeta'[FechaActivo] >= MAX(FechaInicio, FechaMin) && 
			        'dwh Dim_Tarjeta'[FechaActivo] <= MIN(FechaFinal, FechaMax) &&
			        'dwh Dim_Tarjeta'[FechaActivo] <> BLANK() &&  -- Asegura que la fecha no sea nula
			        'dwh Dim_Tarjeta'[FechaActivo] <= FechaMax
			        'dwh Dim_Tarjeta'[FechaActivo] >= MAX(FechaInicio, FechaMin) && 
			        'dwh Dim_Tarjeta'[FechaActivo] <= MIN(FechaFinal, FechaMax) &&
			        'dwh Dim_Tarjeta'[FechaActivo] <> BLANK() &&  -- Asegura que la fecha no sea nula
			        'dwh Dim_Tarjeta'[FechaActivo] <= FechaMax
			    )
			
			-- Devuelve el promedio de tarjetas activadas por día
			RETURN 
			    COALESCE(DIVIDE(TotalTarjetasActivadas, DiasEnRango, "NA"), "NA")  -- Calcula el promedio
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column KeyTarjeta
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: KeyTarjeta

		annotation SummarizationSetBy = Automatic

	column KeyTarjetaAlt
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: KeyTarjetaAlt

		annotation SummarizationSetBy = Automatic

	column Tarjeta
		dataType: string
		summarizeBy: none
		sourceColumn: Tarjeta

		annotation SummarizationSetBy = Automatic

	column FechaCreacion
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: FechaCreacion

		variation Variation
			isDefault
			relationship: 147bdb58-d5bc-47af-8e17-24c5b42cff28
			defaultHierarchy: LocalDateTable_d0f81d21-32c4-440b-92bd-b255d882f733.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FechaActivo
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: FechaActivo

		variation Variation
			isDefault
			relationship: 8d96097c-2685-48b2-b90c-b3b5e9bf1496
			defaultHierarchy: LocalDateTable_1ade2857-01bd-49f9-8176-08e476f004c9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'dwh Dim_Tarjeta' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("40.79.18.177"),
				    Source = Sql.Databases("40.79.18.177"),
				    ApployaltyDWH = Source{[Name="ApployaltyDWH"]}[Data],
				    dwh_Dim_Tarjeta = ApployaltyDWH{[Schema="dwh",Item="Dim_Tarjeta"]}[Data]
				in
				    dwh_Dim_Tarjeta

