table sticker

	measure PromedioStickersActivos = ```
			AVERAGEX(VALUES(sticker[fecha]), [TotalStickersActivos])
			
			```

	measure TotalStickersActivos = ```
			SUM(sticker[actuales])
			
			```
		formatString: 0

	measure VariacionStickersActivos = ```
			
			    DIVIDE(
			        [TotalStickersActivos] - CALCULATE([TotalStickersActivos], DATEADD(sticker[fecha], -1, YEAR)),
			        CALCULATE([TotalStickersActivos], DATEADD(sticker[fecha], -1, YEAR)),
			        0
			    )
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PromedioOtorgadosPorTarjetasActivas = ```
			
			CALCULATE(
			    AVERAGE('sticker'[totales]),
			    'tarjeta'[activo] = "s"
			)
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column idsticker
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: idsticker

		annotation SummarizationSetBy = Automatic

	column fkusuario
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkusuario

		annotation SummarizationSetBy = Automatic

	column fktarjeta
		dataType: string
		sourceProviderType: nvarchar(10)
		summarizeBy: none
		sourceColumn: fktarjeta

		annotation SummarizationSetBy = Automatic

	column fkcliente
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkcliente

		annotation SummarizationSetBy = Automatic

	column totales
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: totales

		annotation SummarizationSetBy = Automatic

	column actuales
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: actuales

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime
		summarizeBy: none
		sourceColumn: fecha

		variation Variation
			isDefault
			relationship: 2f33a84a-601e-4b02-8e15-2c1dff41715a
			defaultHierarchy: LocalDateTable_8035d952-da92-4a87-b3e4-50d149bf7670.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ultvis
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime
		summarizeBy: none
		sourceColumn: ultvis

		variation Variation
			isDefault
			relationship: b0e28d3b-f3d7-42fc-aaab-0b1771bb7999
			defaultHierarchy: LocalDateTable_37aeb087-d9df-4777-8087-31a23f2bb8a6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition sticker = m
		mode: import
		source =
				let
				    Source = Sql.Databases("40.79.18.177"),
				    Apployalty = Source{[Name="Apployalty"]}[Data],
				    dbo_sticker = Apployalty{[Schema="dbo",Item="sticker"]}[Data]
				in
				    dbo_sticker

