table tarjeta

	measure 'Top 3 Distrito' = ```
			
			VAR Ranking = 
			    RANKX(
			        ALL('usuario'[distrito]),
			        CALCULATE(COUNTROWS('tarjeta'), 'tarjeta'[activo] = "s"),
			        ,
			        DESC,
			        Dense
			    )
			RETURN 
			    IF(Ranking <= 3, 
			        CALCULATE(COUNTROWS('tarjeta'), 'tarjeta'[activo] = "s"),
			        BLANK()
			    )
			
			```
		formatString: 0

	measure 'Conteo Activo' = ```
			
			IF(
			    COUNTAX(
			        FILTER(
			            'tarjeta', 
			            'tarjeta'[activo] = "s"
			        ), 
			        'tarjeta'[activo]
			    ) > 0, 
			    COUNTAX(
			        FILTER(
			            'tarjeta', 
			            'tarjeta'[activo] = "s"
			        ), 
			        'tarjeta'[activo]
			    ), 
			    0
			)
			
			```
		formatString: 0

	column idtarjeta
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		summarizeBy: none
		sourceColumn: idtarjeta

		annotation SummarizationSetBy = User

	column codigo
		dataType: string
		sourceProviderType: nvarchar(10)
		summarizeBy: none
		sourceColumn: codigo

		annotation SummarizationSetBy = Automatic

	column fkusuario
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: none
		sourceColumn: fkusuario

		annotation SummarizationSetBy = Automatic

	column fkcliente
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkcliente

		annotation SummarizationSetBy = Automatic

	column fkcamp
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkcamp

		annotation SummarizationSetBy = Automatic

	column feccreacion
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		summarizeBy: none
		sourceColumn: feccreacion

		variation Variation
			isDefault
			relationship: 65b42661-b65c-4579-884c-cfba9a9912b3
			defaultHierarchy: LocalDateTable_69854cb2-12bb-42fe-a3ce-379ee8b82d0b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column completo
		dataType: string
		sourceProviderType: nvarchar(1)
		summarizeBy: none
		sourceColumn: completo

		annotation SummarizationSetBy = Automatic

	column activo
		dataType: string
		sourceProviderType: nvarchar(1)
		summarizeBy: none
		sourceColumn: activo

		annotation SummarizationSetBy = Automatic

	column fecactivo
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		summarizeBy: none
		sourceColumn: fecactivo

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PromedioTarjetas = ```
			AVERAGEX(VALUES(tarjeta[fecactivo]), [Conteo Activo] )
			
			```
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VariacionAnterior
		type: calculated
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":"\n    DIVIDE(\n        [Conteo Activo] - CALCULATE(tarjeta[Conteo Activo], DATEADD(tarjeta[fecactivo], -1, MONTH)),\n        CALCULATE(tarjeta[Conteo Activo], DATEADD(tarjeta[fecactivo], -1, MONTH)),\n        0\n    )"}

		annotation 277cc1b9-af89-4597-8e15-cacc25c0886b = ```
				A circular dependency was detected: tarjeta[VariacionAnterior], tarjeta[PromedioTarjetas], tarjeta[VariacionAnterior].
				
				```

	partition tarjeta = m
		mode: import
		source =
				let
				    Source = Sql.Databases("40.79.18.177"),
				    Apployalty = Source{[Name="Apployalty"]}[Data],
				    dbo_tarjeta = Apployalty{[Schema="dbo",Item="tarjeta"]}[Data]
				in
				    dbo_tarjeta

