table tarjeta

	measure 'Top 3 Distrito' = ```
			
			VAR Ranking = 
			    RANKX(
			        ALL('usuario'[distrito]),
			        CALCULATE(COUNTROWS('tarjeta'), 'tarjeta'[activo] = "s"),
			        ,
			        DESC,
			        Dense
			    )
			RETURN 
			    IF(Ranking <= 3, 
			        CALCULATE(COUNTROWS('tarjeta'), 'tarjeta'[activo] = "s"),
			        BLANK()
			    )
			
			```
		formatString: 0

	measure tarjetasactivas = ```
			
			COUNTAX(
			    FILTER(
			        tarjeta, 
			        tarjeta[activo] = "s"
			    ), 
			    tarjeta[idtarjeta]
			)
			
			```
		formatString: 0

	measure VariacionTarjetas = ```
			
			VAR TotalTarjetasActual = tarjeta[tarjetasactivas]
			VAR TotalTarjetasAnterior = 
			    CALCULATE(
			        tarjeta[tarjetasactivas],
			        DATEADD(Calendario[Date], -1, MONTH)  -- Cambio de periodo (1 mes anterior)
			    )
			RETURN
			    TotalTarjetasActual - TotalTarjetasAnterior
			
			```
		formatString: 0

	measure PromedioTarjetasActivas = ```
			
			VAR TotalTarjetasActivas = 
			    CALCULATE(
			        COUNT(Tarjeta[idtarjeta]), 
			        Tarjeta[activo] = "s"
			    )
			VAR FechaInicio = MIN(Tarjeta[feccreacion])
			VAR FechaFin = MAX(Tarjeta[feccreacion])
			RETURN 
			    TotalTarjetasActivas / DATEDIFF(FechaInicio, FechaFin, DAY)
			
			
			```

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column idtarjeta
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		summarizeBy: none
		sourceColumn: idtarjeta

		annotation SummarizationSetBy = User

	column codigo
		dataType: string
		sourceProviderType: nvarchar(10)
		summarizeBy: none
		sourceColumn: codigo

		annotation SummarizationSetBy = Automatic

	column fkusuario
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: none
		sourceColumn: fkusuario

		annotation SummarizationSetBy = Automatic

	column fkcliente
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkcliente

		annotation SummarizationSetBy = Automatic

	column fkcamp
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkcamp

		annotation SummarizationSetBy = Automatic

	column feccreacion
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		summarizeBy: none
		sourceColumn: feccreacion

		variation Variation
			isDefault
			relationship: 65b42661-b65c-4579-884c-cfba9a9912b3
			defaultHierarchy: LocalDateTable_69854cb2-12bb-42fe-a3ce-379ee8b82d0b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column completo
		dataType: string
		sourceProviderType: nvarchar(1)
		summarizeBy: none
		sourceColumn: completo

		annotation SummarizationSetBy = Automatic

	column activo
		dataType: string
		sourceProviderType: nvarchar(1)
		summarizeBy: none
		sourceColumn: activo

		annotation SummarizationSetBy = Automatic

	column fecactivo
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		summarizeBy: none
		sourceColumn: fecactivo

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PromedioTarjetas = ```
			
			AVERAGEX(
			    VALUES(Tarjeta[fecactivo]), 
			    CALCULATE(
			        COUNTROWS(
			            FILTER(
			                Tarjeta, 
			                Tarjeta[activo] = "s"
			            )
			        )
			    )
			)
			
			```
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tarjetas_activadas = ```
			
			COUNTAX(
			    FILTER(
			        tarjeta, 
			        tarjeta[activo] = "s" && RELATED(usuario[activo]) = "s"
			    ), 
			    tarjeta[idtarjeta]
			)
			
			```
		formatString: 0
		summarizeBy: none

		annotation SummarizationSetBy = User

	partition tarjeta = m
		mode: import
		source =
				let
				    Source = Sql.Databases("40.79.18.177"),
				    Apployalty = Source{[Name="Apployalty"]}[Data],
				    dbo_tarjeta = Apployalty{[Schema="dbo",Item="tarjeta"]}[Data]
				in
				    dbo_tarjeta

