table tracking_stickers

	measure PromedioStickersEntregados = ```
			
			AVERAGEX(
			    VALUES(tracking_stickers[fecha]), 
			    [TotalStickersEntregados]
			)
			```

	measure TotalStickersEntregados = ```
			SUM(tracking_stickers[stickers])
			
			```
		formatString: 0

	measure VariacionStickersEntregados = ```
			
			    DIVIDE(
			        [TotalStickersEntregados] - CALCULATE([TotalStickersEntregados], DATEADD(Calendario[Date], -1, YEAR)),
			        CALCULATE([TotalStickersEntregados], DATEADD(Calendario[Date], -1, YEAR)),
			        0
			    )
			
			
			```
		formatString: 0

	column idtracking
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: idtracking

		annotation SummarizationSetBy = Automatic

	column fkcliente
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkcliente

		annotation SummarizationSetBy = Automatic

	column fktienda
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fktienda

		annotation SummarizationSetBy = Automatic

	column fkusuario
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: fkusuario

		annotation SummarizationSetBy = Automatic

	column fktarjeta
		dataType: string
		sourceProviderType: nvarchar(10)
		summarizeBy: none
		sourceColumn: fktarjeta

		annotation SummarizationSetBy = Automatic

	column stickers
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: stickers

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		summarizeBy: none
		sourceColumn: fecha

		variation Variation
			isDefault
			relationship: 8a9b943b-3cd3-44a5-ba87-fb075e30a5aa
			defaultHierarchy: LocalDateTable_fdcbeae9-95ad-4b44-b523-f807ee3c4412.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition tracking_stickers = m
		mode: import
		source =
				let
				    Source = Sql.Databases("40.79.18.177"),
				    Apployalty = Source{[Name="Apployalty"]}[Data],
				    dbo_tracking_stickers = Apployalty{[Schema="dbo",Item="tracking_stickers"]}[Data]
				in
				    dbo_tracking_stickers

