name: Generate PBIX File

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  generate-pbix:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download pbi-tools
      run: |
        Invoke-WebRequest -Uri https://github.com/pbi-tools/pbi-tools/releases/download/1.2.0/pbi-tools.1.2.0.zip -OutFile pbi-tools.zip
        Expand-Archive -Path pbi-tools.zip -DestinationPath pbi-tools

    - name: Add pbi-tools to PATH
      run: echo "pbi-tools" >> $env:GITHUB_PATH

    - name: Generate PBIX file
      run: pbi-tools compile Dashboard/ PBIT PBIT
